name: base
channels:
  - pytorch
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - _anaconda_depends=2019.03
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - affine=2.3.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.4
  - asn1crypto=1.4.0
  - astroid=2.3.3
  - astropy=3.2.3
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - babel=2.8.1
  - backcall=0.2.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.9.3
  - bitarray=1.6.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.20.1
  - bokeh=1.4.0
  - boost-cpp=1.72.0
  - boto=2.49.0
  - bottleneck=1.3.1
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cartopy=0.17.0
  - catalogue=1.0.0
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.9.2
  - conda-build=3.17.8
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.1.1
  - console_shortcut=0.1.1
  - contextily=1.0.0
  - contextlib2=0.6.0.post1
  - convertdate=2.3.0
  - cryptography=2.8
  - cudatoolkit=10.2.89
  - curl=7.67.0
  - cycler=0.10.0
  - cymem=2.0.4
  - cython=0.29.21
  - cython-blis=0.4.1
  - cytoolz=0.11.0
  - dask=2.8.0
  - dask-core=2.8.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distributed=2.9.1
  - docutils=0.16
  - entrypoints=0.3
  - ephem=3.7.7.1
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fastcache=1.1.0
  - fbprophet=0.6
  - filelock=3.0.12
  - fiona=1.8.4
  - flask=1.1.2
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.3
  - future=0.18.2
  - gdal=2.3.3
  - geographiclib=1.50
  - geopandas=0.6.3
  - geoplot=0.4.1
  - geopy=1.22.0
  - geos=3.7.1
  - get_terminal_size=1.0.0
  - gevent=20.9.0
  - glob2=0.7
  - graphviz=2.38
  - greenlet=0.4.17
  - h5py=2.9.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - holidays=0.10.3
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.6.1
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.3
  - jupyterlab_server=1.0.6
  - kealib=1.4.7
  - keyring=21.4.0
  - kiwisolver=1.3.0
  - korean_lunar_calendar=0.2.1
  - krb5=1.16.4
  - lazy-object-proxy=1.5.2
  - libarchive=3.4.2
  - libboost=1.67.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblief=0.10.1
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.28.0
  - locket=0.2.0
  - lunarcalendar=0.0.9
  - lxml=4.6.2
  - lz4-c=1.9.2
  - lzo=2.10
  - mapclassify=2.3.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mercantile=1.1.5
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mlxtend=0.17.3
  - mock=3.0.5
  - more-itertools=8.6.0
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multipledispatch=0.6.0
  - munch=2.5.0
  - murmurhash=1.0.2
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - networkx=2.5
  - ninja=1.10.2
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.2
  - numba=0.43.1
  - numexpr=2.7.0
  - numpy=1.17.3
  - numpy-base=1.17.3
  - numpydoc=0.9.1
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - owslib=0.19.2
  - packaging=19.2
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - partd=1.1.0
  - path=15.0.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3
  - pkginfo=1.6.1
  - plac=0.9.6
  - pluggy=0.13.1
  - ply=3.11
  - preshed=3.0.2
  - proj4=5.2.0
  - prometheus_client=0.9.0
  - prompt_toolkit=2.0.10
  - psutil=5.7.2
  - py=1.9.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydot=1.4.1
  - pyepsg=0.4.0
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pykdtree=1.3.1
  - pylint=2.4.4
  - pymeeus=0.3.7
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.15.5
  - pyshp=2.1.2
  - pysocks=1.7.1
  - pystan=2.17.1.0
  - pytables=3.6.1
  - pytest=5.2.4
  - pytest-arraydiff=0.3
  - pytest-astropy=0.6.0
  - pytest-astropy-header=0.1.1
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-graphviz=0.15
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytorch=1.5.1
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - rasterio=1.0.21
  - requests=2.22.0
  - rope=0.18.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.15.0
  - scikit-learn=0.22.1
  - scikit-surprise=1.1.1
  - scipy=1.4.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=50.3.2
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.0.0
  - snuggs=1.4.7
  - sortedcollections=1.2.1
  - sortedcontainers=2.3.0
  - soupsieve=2.0.1
  - spacy=2.3.1
  - sphinx=2.2.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=3.3.6
  - spyder-kernels=0.5.2
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - srsly=1.0.2
  - sympy=1.6.2
  - tbb=2020.3
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - thinc=7.4.1
  - tk=8.6.10
  - toolz=0.11.1
  - torchvision=0.6.1
  - tornado=6.1
  - tqdm=4.54.0
  - traitlets=4.3.3
  - unicodecsv=0.14.1
  - urllib3=1.24.2
  - wasabi=0.8.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.0
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xerces-c=3.2.3
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.2.0
  - zstd=1.4.5
  - pip:
    - appdirs==1.4.3
    - cfgv==3.2.0
    - cliff==3.1.0
    - cmd2==0.8.9
    - crowdai-api==0.1.22
    - debtcollector==2.0.0
    - dill==0.3.3
    - distlib==0.3.1
    - dogpile-cache==0.9.0
    - en-core-web-sm==2.3.1
    - fasttext==0.9.1
    - flatland-rl==2.2.1
    - gym==0.14.0
    - hdf5storage==0.1.15
    - identify==1.5.3
    - importlib-resources==1.5.0
    - ipynb==0.5.1
    - iso8601==0.1.12
    - jmespath==0.9.5
    - jsonpatch==1.25
    - jsonpointer==2.0
    - keystoneauth1==4.0.0
    - mat4py==0.4.3
    - mat73==0.45
    - msgpack-numpy==0.4.6.post0
    - netaddr==0.7.19
    - netifaces==0.10.9
    - nodeenv==1.5.0
    - oauthlib==3.1.0
    - openstacksdk==0.46.0
    - os-service-types==1.7.0
    - osc-lib==2.0.0
    - oslo-config==8.0.1
    - oslo-i18n==4.0.0
    - oslo-serialization==3.1.0
    - oslo-utils==4.1.0
    - padasip==1.1.1
    - pandas==1.1.4
    - pbr==5.4.4
    - pre-commit==2.7.1
    - prettytable==0.7.2
    - pyarrow==1.0.0
    - pybind11==2.4.3
    - pydub==0.23.1
    - pyglet==1.3.2
    - pyperclip==1.8.0
    - pytest-runner==5.2
    - python-cinderclient==6.0.0
    - python-gitlab==2.4.0
    - python-keystoneclient==3.22.0
    - python-novaclient==16.0.0
    - python-openstackclient==5.2.0
    - recordtype==1.3
    - redis==3.5.3
    - requests-oauthlib==1.3.0
    - requestsexceptions==1.4.0
    - rfc3986==1.3.2
    - simplejson==3.17.0
    - statsmodels==0.12.1
    - stevedore==1.32.0
    - suds-jurko==0.6
    - suds-py3==1.4.1.0
    - suds-requests==0.4.0
    - svgutils==0.3.1
    - tick==0.7.0.1
    - timeout-decorator==0.4.1
    - toml==0.10.1
    - tox==3.18.0
    - translate==3.5.0
    - typed-ast==1.4.1
    - virtualenv==20.0.28
prefix: C:\Users\Isabelle\Anaconda3
